#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

sudo apt-get update \
  && apt-get install -y libxss1 \
  && add-apt-repository ppa:webupd8team/atom \
  && apt-get update \
  && apt-get install -y --no-install-recommends atom
