#!/bin/bash
# See http://breandan.net/2014/08/18/shell-script/
CODE=IIC
URL="https://data.services.jetbrains.com/products/download?platform=linux&code=$CODE"

# Get location header for file URL
HEADERS=$(wget -qS --max-redirect 0 --spider "$URL" 2>&1)
LOCATION=$(echo "$HEADERS" | tac | grep -m 1 "Location: ")
FILE_URL=$(echo "$LOCATION" | sed 's/.*Location: //')
VERSION=$(echo "$FILE_URL" | sed -En 's/.*\/(.*).tar.gz/\1/p')

mkdir -p ~/bin/$VERSION
curl -L $FILE_URL | tar xz --strip 1 --directory ~/bin/$VERSION
rm -f ~/bin/idea
ln -s ~/bin/$VERSION/bin/idea.sh ~/bin/idea
