#!/bin/bash
VER=ideaIC-2017.1

set -e

sudo apt install -y openjdk-8-jdk
mkdir -p ~/bin/$VER
curl -L https://download.jetbrains.com/idea/$VER.tar.gz | tar xz --strip 1 --directory ~/bin/$VER
rm -f ~/bin/idea
ln -s ~/bin/$VER/bin/idea.sh ~/bin/idea
