#!/bin/bash

set -e

DEBIAN_FRONTEND=noninteractive
NOMACHINE=https://download.nomachine.com/download/6.4/Linux/nomachine_6.4.6_1_amd64.deb

sudo apt update \
&& curl -fSL $NOMACHINE -o /tmp/nomachine.deb \
&& sudo dpkg --install /tmp/nomachine.deb \
&& rm /tmp/*.deb \
&& mkdir -p $HOME/.nx/config \
&& cp $HOME/.ssh/authorized_keys $HOME/.nx/config/authorized.crt \
&& chmod 600 $HOME/.nx/config/authorized.crt

#sudo sed -i 's|DefaultDesktopCommand.*|DefaultDesktopCommand "/usr/bin/startlxde"|g' /usr/NX/etc/node.cfg

# SSH
#sudo sed -i '/#ClientConnectionMethods /s/^#//g' /usr/NX/etc/server.cfg
#sudo sed -i 's/ClientConnectionMethods NX$/ClientConnectionMethods NX,SSH/g' /usr/NX/etc/server.cfg

#sudo sed -i '/#ConnectPolicy /s/^#//g' /usr/NX/etc/server.cfg

# Boot to console, not GUI
#sudo systemctl enable multi-user.target
#sudo systemctl set-default multi-user.target

sudo /etc/NX/nxserver --startup
