#!/bin/bash

if [ "$(whoami)" != "root" ]; then
	echo "Sorry, you are not root."
	exit 1
fi

DEBIAN_FRONTEND=noninteractive
ME=$SUDO_USER

apt update \
&& apt install -y --no-install-recommends lxde \
&& curl -L http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.54_1_amd64.deb -o /tmp/nomachine.deb \
&& dpkg --install /tmp/nomachine.deb \
&& rm /tmp/*.deb \
&& mkdir -p $HOME/.nx/config \
&& cp $HOME/.ssh/authorized_keys $HOME/.nx/config/authorized.crt \
&& chmod 600 $HOME/.nx/config/authorized.crt \
&& chown -R $ME:$ME $HOME/.nx \
&& sed -i 's|DefaultDesktopCommand.*|DefaultDesktopCommand "/usr/bin/startlxde"|g' /usr/NX/etc/node.cfg \
&& /etc/NX/nxserver --startup
