#!/bin/bash

set -e

DEBIAN_FRONTEND=noninteractive

sudo apt update \
&& sudo apt install -y curl lxde \
&& curl -L http://download.nomachine.com/download/5.1/Linux/nomachine_5.1.62_1_amd64.deb -o /tmp/nomachine.deb \
&& sudo dpkg --install /tmp/nomachine.deb \
&& rm /tmp/*.deb \
&& mkdir -p $HOME/.nx/config \
&& cp $HOME/.ssh/authorized_keys $HOME/.nx/config/authorized.crt \
&& chmod 600 $HOME/.nx/config/authorized.crt

sed -i 's|DefaultDesktopCommand.*|DefaultDesktopCommand "/usr/bin/startlxde"|g' /usr/NX/etc/node.cfg

sed -i '/#ClientConnectionMethods /s/^#//g' /usr/NX/etc/server.cfg
sed -i 's/ClientConnectionMethods NX$/ClientConnectionMethods NX,SSH/g' /usr/NX/etc/server.cfg

sed -i '/#ConnectPolicy /s/^#//g' /usr/NX/etc/server.cfg

sudo systemctl enable multi-user.target --force
sudo systemctl set-default multi-user.target

sudo /etc/NX/nxserver --startup
