#!/bin/bash

VER=rclone-v1.34-linux-amd64

set -e

sudo apt update
sudo apt install -y --no-install-recommends fuse ca-certificates unzip

mkdir -p ~/bin/$VER
curl -L -o /tmp/$VER.zip http://downloads.rclone.org/${VER}.zip
unzip /tmp/$VER.zip -d ~/bin/
rm /tmp/$VER.zip
ln -s ~/bin/$VER/rclone ~/bin/rclone
