#!/bin/bash
DIR='sbt-0.13.15'
mkdir -p ~/bin/$DIR
curl -L https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz | tar xz --strip 1 --directory ~/bin/$DIR
rm ~/bin/sbt
ln -s ~/bin/$DIR/bin/sbt ~/bin/sbt
