#!/bin/bash

sudo dpkg --add-architecture i386 \
  && apt-get -q update

sudo apt-get install \
  libasound2:i386 \
  libc6:i386 \
  libfreetype6:i386 \
  libgcc1:i386 \
  libsm6:i386 \
  libxdamage1:i386 \
  libxext6:i386 \
  libxfixes3:i386 \
  libxrandr2:i386 \
  libxrender1:i386 \
  libxtst6:i386 \
  zlib1g:i386 \
  libjpeg8:i386 \
  libexpat1:i386 \
  fonts-liberation:i386 \
  libfontconfig1:i386 \
  fontconfig-config:i386 \
  ucf \
  libdbus-1-3:i386 \
  libjpeg62:i386 \
  libxinerama1:i386 \
  libpng12-0:i386

  curl -L http://download.teamviewer.com/download/teamviewer_i386.tar.xz \
   | tar xz --directory ~/opt
