#!/bin/bash

set -e
DEBIAN_FRONTEND=noninteractive

sudo dpkg --add-architecture i386
sudo apt -y update

sudo apt -y install \
  xz-utils libc6:i386 libdbus-1-3 libasound2 libsm6 libxfixes3 \
  libdbus-1-3:i386 libasound2:i386 libexpat1:i386 libfontconfig1:i386 \
  libfreetype6:i386 libjpeg62:i386 libpng12-0:i386 libsm6:i386 \
  libxdamage1:i386 libxext6:i386 libxfixes3:i386 libxinerama1:i386 \
  libxrandr2:i386 libxrender1:i386 libxtst6:i386 zlib1g:i386

mkdir -p ~/bin

curl -L http://download.teamviewer.com/download/teamviewer_i386.tar.xz \
   | tar -xJ --directory ~/bin
mv ~/bin/teamviewer ~/bin/teamviewer_i386
ln -s ~/bin/teamviewer_i386/tv_bin/script/teamviewer ~/bin/teamviewer
~/bin/teamviewer_i386/tv-setup checklibs
