#!/bin/bash
SOURCES='/etc/apt/sources.list'

if [ "$(whoami)" != "root" ]; then
	echo "Sorry, you are not root."
	exit 1
elif [ ! -f "$SOURCES" ]; then
	echo "Sources file (${SOURCES} )not found, exiting"
	exit 1
fi

if grep -qi "cran" "${SOURCES}"; then
	echo "CRAN already referenced in ${SOURCES}"
else
	CODENAME=`lsb_release --codename | cut -f2`
	echo "deb http://cran.ma.imperial.ac.uk/bin/linux/ubuntu ${CODENAME}/" >> /etc/apt/sources.list \
	&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
fi

apt-get update
apt-get install -y r-base

R --no-save << EOF
install.packages(
	c(
		"ggplot2",
		"reshape2",
		"jsonlite",
		"plyr"
	),
	dependencies=T,
	repos="http://cran.ma.imperial.ac.uk"
)
quit("no")
EOF
