#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive

sudo apt-mark hold xscreensaver

sudo apt -y install \
  unattended-upgrades \
  lxqt-core \
  lxqt-qtplugin \
  lxqt-config \
  sddm \
  qterminal \
  pavucontrol-qt \
  open-vm-tools-desktop \
  snapd \
  htop
